// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransporteV1API.Data;

#nullable disable

namespace TransporteV1API.Migrations
{
    [DbContext(typeof(TransporteContext))]
    partial class TransporteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TransporteV1API.Modals.Camiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Discricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OMNLink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Camiaos", (string)null);
                });

            modelBuilder.Entity("TransporteV1API.Modals.Financiamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Financiador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdCamiao")
                        .HasColumnType("int");

                    b.Property<int>("QtdParcelas")
                        .HasColumnType("int");

                    b.Property<float>("ValorMensal")
                        .HasColumnType("float");

                    b.Property<float>("ValorPago")
                        .HasColumnType("float");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCamiao")
                        .IsUnique();

                    b.ToTable("Financiamentos");
                });

            modelBuilder.Entity("TransporteV1API.Modals.Seguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCamiao")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCamiao")
                        .IsUnique();

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("TransporteV1API.Modals.Financiamento", b =>
                {
                    b.HasOne("TransporteV1API.Modals.Camiao", "camiao")
                        .WithOne("financiamento")
                        .HasForeignKey("TransporteV1API.Modals.Financiamento", "IdCamiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("camiao");
                });

            modelBuilder.Entity("TransporteV1API.Modals.Seguro", b =>
                {
                    b.HasOne("TransporteV1API.Modals.Camiao", "camiao")
                        .WithOne("Seguro")
                        .HasForeignKey("TransporteV1API.Modals.Seguro", "IdCamiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("camiao");
                });

            modelBuilder.Entity("TransporteV1API.Modals.Camiao", b =>
                {
                    b.Navigation("Seguro")
                        .IsRequired();

                    b.Navigation("financiamento")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
